[[headers]]
  for = "/fonts/*"
  [headers.values]
  cache-control = "max-age=604800" # 1 week

[[headers]]
  for = "/images/*"
  [headers.values]
  cache-control = "max-age=604800" # 1 week

[[headers]]
  for = "/favicon.ico"
  [headers.values]
  cache-control = "max-age=604800" # 1 week

[[redirects]]
from = "/guide/inline-queries.html"
to = "/plugins/inline-query.html"
status = 301

[[redirects]]
from = "/*/guide/inline-queries.html"
to = "/:splat/plugins/inline-query.html"
status = 301

[[redirects]]
from = "/*"
to = "/404.html"
status = 404
force = true

[[redirects]]
from = "/es/*"
to = "/es/404.html"
status = 404
force = true

[[redirects]]
from = "/id/*"
to = "/id/404.html"
status = 404
force = true

[[redirects]]
from = "/uk/*"
to = "/uk/404.html"
status = 404
force = true

[[redirects]]
from = "/zh/*"
to = "/zh/404.html"
status = 404
force = true
