name: Deploy

on:
  push:
    paths:
      - "notifier/**"

jobs:
  deploy:
    if: github.repository_owner == 'grammyjs'
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v3

      - uses: denoland/deployctl@v1
        with:
          project: sour-newt-93
          entrypoint: main.ts
          root: notifier
